# Generated by Django 3.0.5 on 2023-05-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprescriptiondata',
            name='input_img',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/uploaded_prescriptions'),
        ),
    ]
