# Generated by Django 3.0.5 on 2023-05-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_patientprescriptiondata_cropped_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprescriptiondata',
            name='cropped_image',
            field=models.ImageField(blank=True, null=True, upload_to='prescriptions/cropped_images'),
        ),
    ]
